### ISSUE TITLE
你们是怎样给图片添加雾的效果？借鉴下你们加雾的方法，3q

### ISSUE THREAD

**Issue by GingerCohle** [HUSTSYJ/DA_dahazing#2]
感觉你们的并不是拍出来的

**Comment by GingerCohle** [comment]
How to add haze into our own dataset

**Comment by zhangbaijin** [comment]
I also want to know this question. - -

**Comment by GingerCohle** [comment]
> I also want to know this question. - -

不过这貌似是公开数据集。。。。。。

**Comment by Four97** [comment]
> 
> 
> > I also want to know this question. - -
> 
> 不过这貌似是公开数据集。。。。。。

你知道公开数据及reside是怎么做的吗，是直接利用公式加吗？或者您后续是怎么做的呢
